--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/OutiServerSensouPlugin
build-by-default: true
branches:
  - master
projects:
  AutoUpdater:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
...