name: AutoUpdater
main: Ken_Cir\AutoUpdater\AutoUpdater
description: PocketMineを自動でアップデートするプラグイン
author: Ken_Cir
version: 1.0.0
api: 4.0.0
extensions:
  - pcntl

permissions:
  outiserver.checkupdate.command:
    description: CheckUpdate CommandPermissions
    default: op